### ISSUE TITLE
Extending chars

### ISSUE THREAD

**Issue by McKay89** [yulanggong/Wordz-Solver#10]
Hi.

I'm decided to write here, i stucked when i tried  to extend the W.chars variable.

With the extended chars seems like this: `W.chars = 'AÁBCDEÉFGHIÍJKLMNOÓÖŐPQRSTUÚÜŰVWXYZ';` (ÁÉÍÓÖŐÚÜŰ)

Successfully created the dict.js but i think the decode function not working with these accents.
The browser console log the following: 

> Uncaught SyntaxError: Expected ':' after property name in JSON at position 9
>     at JSON.parse (<anonymous>)
>     at W.decode (wordzsolver.js:104:14)
>     at dict.js:4:13
>     at dict.js:5:3

If you have any idea or solution, please share with me.

Thanks,
McKay89

**Comment by yulanggong** [comment]
The original encode/decode functions are too wacky. If you don't care about the size of `dict.js` you can rewrite these functions.

```js
W.encode = function(dict){
	return JSON.stringify(dict);
}

W.decode = function(dict){
	return JSON.parse(dict);
}
```

**Comment by McKay89** [comment]
Thank you, this works fine. :)
